Repository Mai-Sigurd/disaster-routing-simulator, pull requests merged in 2025-02, with the labels that each got.

#5 Add data loaders for OSM and GeoJSON data
  .gitignore
  data/danger_zones/dangerzone_amager.geojson
  poetry.lock
  pyproject.toml
  src/data_loader/__init__.py
  src/data_loader/danger_zones.py
  src/data_loader/osm.py
  src/main.py
Labels: enhancement

#9 Implement Dijkstra method v1
  .vscode/settings.json
  src/interface.py
  src/routes/routes.py
  tests/routes/test_route_to_safety.py
Labels: enhancement

#12 Departure times
  .gitignore
  pyproject.toml
  src/routes/route.py
  src/routes/shortestpath.py
  tests/routes/test_introduce_departure_times.py
  tests/routes/test_route_to_safety.py
Labels: enhancement

#15 Quickestpath
  src/data_loader/danger_zones.py
  src/data_loader/population/population.py
  src/data_loader/population/populationGeoDataFrame.py
  src/routes/fastestpath.py
  tests/data_loader/test_danger_zones.py
  tests/routes/test_fastest_path.py
  tests/routes/test_route_to_safety.py
Labels: bug, enhancement

#11 Generate MATSim input files
  README.md
  data/matsim/.gitignore
  data/matsim/config.xml
  poetry.lock
  pyproject.toml
  src/main.py
  src/matsim_io/__init__.py
  src/matsim_io/writers.py
  tests/conftest.py
  tests/data_loader/__init__.py
  tests/data_loader/test_osm.py
  tests/matsim_io/test_writers.py
Labels: enhancement

#18 Project coordinates onto WGS84 coordinate system
  data/matsim/config.xml
  src/matsim_io/__init__.py
Labels: enhancement

#24 Add oneway attribute to edges in the test graph
  tests/conftest.py
  tests/matsim_io/test_writers.py
Labels: bug
