Repository Mai-Sigurd/disaster-routing-simulator, pull requests merged in 2025-03, with the labels that each got.

#26 Add matsim evacuation algorithm
  src/matsim_io/__init__.py
  src/matsim_io/writers.py
  tests/matsim_io/test_writers.py
Labels: enhancement

#29 Read bounding box from data directory
  data/bbox/cph_bbox.geojson
  src/data_loader/osm.py
  tests/data_loader/test_osm.py
Labels: enhancement

#30 Refactor population
  src/data_loader/population/__init__.py
  src/data_loader/population/population.py
  src/data_loader/population/utils.py
  src/main.py
  src/routes/route.py
  tests/data_loader/population/test_population.py
Labels: documentation, enhancement

#33 Disable innovative re-routing
  data/matsim/config.xml
Labels: bug

#27 add simple gui
  README.md
  poetry.lock
  pyproject.toml
  src/data_loader/__init__.py
  src/data_loader/danger_zones.py
  src/data_loader/osm.py
  src/data_loader/population/__init__.py
  src/gui/__init__.py
  src/gui/constants.py
  src/gui/controller.py
  src/gui/fields.py
  src/gui/font/open-sans/OpenSans-Bold.ttf
  src/gui/font/open-sans/OpenSans-Italic.ttf
  src/gui/font/open-sans/OpenSans-Regular.ttf
  src/input_data.py
  src/interface.py
  src/main.py
  tests/conftest.py
  tests/data_loader/test___init__.py
  tests/data_loader/test_osm.py
  tests/routes/test_fastest_path.py
  tests/routes/test_introduce_departure_times.py
  tests/test_input_data.py
Labels: enhancement

#28 Configure dashboard
  data/danger_zones/dangerzone_lillebitteamager.geojson
  data/matsim/.gitignore
  data/matsim/config.xml
  poetry.lock
  pyproject.toml
  simulator/pom.xml
  simulator/src/main/java/org/disaster/routing/DisasterRoutingDashboard.java
  simulator/src/main/java/org/disaster/routing/DisasterRoutingModule.java
  simulator/src/main/java/org/disaster/routing/Main.java
  simulator/src/main/java/org/disaster/routing/analysis/TripPurposeBy10Min.java
Labels: enhancement

#36 Add default strategy without re-routing
  data/matsim/config.xml
Labels: bug
